---
# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  # Labels of self-hosted runner
  labels: []

shellcheck:
  # Enable shellcheck integration
  enable: true
  # Only report errors, ignore info/warning/style
  severity: error
