site_name: OpenShift Provider Compatibility Tool | OPCT
site_description: OpenShift Provider Compatibility Tool
site_url: https://redhat-openshift-ecosystem.github.io/provider-certification-tool
repo_url: https://github.com/redhat-openshift-ecosystem/provider-certification-tool
edit_uri: edit/main/docs/
docs_dir: ./docs
dev_addr: 127.0.0.1:8000

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # - pymdownx.tabbed:
  #     alternate_style: true 

plugins:
  - diagrams:
      file_extension: ".diagram.py"
      max_workers: 5
  - search

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
  features:
    #- toc.integrate
    - navigation.top
    - navigation.tabs
    - navigation.top

nav:
  - Home:
    - README.md
  - Review:
    - Home: review/index.md
    - OPCT Rules: review/rules.md
    - "Installation Review": user-installation-review.md
    - "Troubleshooting": troubleshooting-guide.md
    - "Installation Checklist": user-installation-checklist.md
    - Review Guide: support-guide.md
  - Validation Guides:
    - "User Guide": "user.md"
    - "Disconnected Installations": user-installation-disconnected.md
  - Contribute: TODO.md
  - Developement:
    - Development Guide: dev.md
    - Diagrams:
      - diagrams/index.md
      - diagrams/opct-sequence.md
      - "Reference Architecture": diagrams/ocp-architecture-reference.md
  - CHANGELOG: CHANGELOG.md
