site_name: OpenShift Provider Certification Tool
site_description: >-
  OpenShift Provider Certification Tool | Guide
site_url: https://redhat-openshift-ecosystem.github.io/provider-certification-tool
repo_url: https://github.com/redhat-openshift-ecosystem/provider-certification-tool
edit_uri: edit/main/docs/
docs_dir: ./docs

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
nav:
  - "User Guide":
      - "User Guide": "user.md"
      - "Installation Checklist": user-installation-checklist.md
      - "Installation Review": user-installation-review.md
      - "Troubleshooting": troubleshooting-guide.md
      - "Results Review": user-results-review.md
  - "Support Guide":
      - "Support Guide": support-guide.md
  - "Developer Guide":
      - "Development Guide": dev.md
