site_name: OpenShift Provider Certification Guide
repo_url: https://github.com/redhat-openshift-ecosystem/provider-certification-tool
edit_uri: edit/main/docs/
docs_dir: ./docs

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
nav:
  - "User Guide":
      - "User Guide": "user.md"
  - "Support Guide":
      - "Support Guide": TODO.md
  - "Developer Guide":
      - "Development Guide": dev.md
