site_name: OpenShift Provider Certification Tool
site_description: >-
  OpenShift Provider Certification Tool | Guide
site_url: https://redhat-openshift-ecosystem.github.io/provider-certification-tool
repo_url: https://github.com/redhat-openshift-ecosystem/provider-certification-tool
edit_uri: edit/main/docs/
docs_dir: ./docs
dev_addr: 127.0.0.1:8000

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - diagrams:
      file_extension: ".diagram.py"
      max_workers: 5
  - search

theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
  features:
    #- toc.integrate
    - navigation.top
nav:
  - User Guides:
    - "User Guide": "user.md"
    - "Installation Checklist": user-installation-checklist.md
    - "Installation Review": user-installation-review.md
    - "Disconnected Installations": user-installation-disconnected.md
    - "Troubleshooting": troubleshooting-guide.md
  - Support Guides:
    - Support Guide: support-guide.md
  - Developer Guides:
    - Development Guide: dev.md
    - Diagrams:
      - diagrams/index.md
      - diagrams/opct-sequence.md
      - "Reference Architecture": diagrams/ocp-architecture-reference.md
