
FROM docker.io/golang:1.21-alpine AS builder
ARG RELEASE_TAG
RUN apk add --no-cache --update make git
WORKDIR /go/src/github.com/redhat-openshift-ecosystem/provider-certification-tool
COPY . .
RUN make build-linux-amd64 RELEASE_TAG=${RELEASE_TAG}

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.8-860
LABEL io.k8s.display-name="OPCT" \
      io.k8s.description="OpenShift/OKD Conformance Tool is designed to run conformance suites to validate custom installations." \
      io.opct.tags="opct,conformance,openshift,tests,e2e" \
      io.opct.os="linux" io.opct.arch="amd64"

COPY --from=builder \
      /go/src/github.com/redhat-openshift-ecosystem/provider-certification-tool/build/opct-linux-amd64 \
      /usr/bin/

CMD ["/usr/bin/opct-linux-amd64"]
