# Build opct-runner

# https://github.com/mtulio/ansible-collection-okd-installer/pull/22
# https://github.com/mtulio/ansible-collection-okd-installer/actions/runs/4008306599
FROM quay.io/mrbraga/okd-installer:0.0.0-ci.212-4120332897

COPY --from=quay.io/ocp-cert/tools:latest /usr/bin/oc /usr/bin/

ENV ANSIBLE_LOG_PATH=/root/.ansible/okd-installer/opct-runner.log

WORKDIR /opct-runner

ADD ./ansible.cfg ./
ADD ./inventories/* ./inventories/
ADD ./opct-*.yaml .
