# Build opct-runner

# https://github.com/mtulio/ansible-collection-okd-installer/pull/26
FROM quay.io/mrbraga/okd-installer:0.0.0-dev.92-5763394953

COPY --from=quay.io/ocp-cert/tools:latest /usr/bin/oc /usr/bin/
COPY --from=quay.io/ocp-cert/tools:latest /usr/bin/jq /usr/bin/

ENV ANSIBLE_LOG_PATH=/opt/okd-installer/opct-runner.log

WORKDIR /opct-runner

ADD ./ansible.cfg ./
ADD ./inventories/* ./inventories/
ADD ./opct-*.yaml .
