name: "OPCT"

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    tags:
      - '*'

jobs:
  go-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      # https://github.com/golangci/golangci-lint-action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=10m

  go-static:
    name: "go-staticcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: '1.21'
      - name: Run static code analysis
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.7"
          install-go: false

  go-test:
    name: go-test
    runs-on: ubuntu-latest
    needs:
    - go-lint
    - go-static
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run unit tests
        run: make test

  go-vet:
    name: "go-vet"
    runs-on: ubuntu-latest
    needs:
    - go-lint
    - go-static
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Run go vet
        run: make vet

  build:
    name: "build-artifact"
    runs-on: ubuntu-latest
    needs:
    - go-test
    - go-vet
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git -y

      - name: Build (OS=linux-amd64)
        env:
          OS_ARCH: linux-amd64
        run: |
          make clean
          make linux-amd64-container
          make build-${OS_ARCH}

      - name: Save artifacts (OS=linux-amd64)
        uses: actions/upload-artifact@v3
        with:
          name: opct-linux-amd64
          path: |
            build/opct-*

      - name: Build (OS=darwin-arm64)
        env:
          OS_ARCH: darwin-arm64
        run: |
          make clean
          make build-${OS_ARCH}

      - name: Save artifacts (OS=darwin-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: opct-darwin-arm64
          path: |
            build/opct-*
