name: "OPCT"

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    tags:
      - '*'

jobs:
  # TODO: add go-lint
  go-test:
    name: "go-test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run unit tests
        run: make test

      - name: Run go vet
        run: make vet

      - name: Run static code analysis
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

  go-vet:
    name: "go-vet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run go vet
        run: make vet

  go-static:
    name: "go-staticcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run static code analysis
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"