name: "OPCT"

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    tags:
      - '*'

jobs:
  go-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: false
      # https://github.com/golangci/golangci-lint-action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=10m

  go-static:
    name: "go-staticcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Run static code analysis
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"

  go-test:
    name: go-test
    runs-on: ubuntu-latest
    needs:
    - go-lint
    - go-static
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Run unit tests
        run: make test

  go-vet:
    name: "go-vet"
    runs-on: ubuntu-latest
    needs:
    - go-lint
    - go-static
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Run go vet
        run: make vet