name: "Go"

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    tags:
      - '*'

jobs:
  static:
    name: "Run Continuous Integration"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Verify bindata was generated
        run: |
          go install github.com/go-bindata/go-bindata/go-bindata@latest
          set -xe
          ./hack/update-generated-bindata.sh
          set +ex
          # bypassing CI check for pkg/assets/bindata.go due go-bindata issues with ioutils
          # https://issues.redhat.com/browse/OPCT-199
          git checkout pkg/assets/bindata.go
          git diff --exit-code

      - name: Run unit tests
        run: make test

      - name: Run go vet
        run: make vet

      - name: Run static code analysis
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"