name: "OPCT"

on:
  pull_request:
    branches:
      - main
      - release-*
  push:
    tags:
      - '*'

jobs:
  go-lint:
    name: go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: false
      # https://github.com/golangci/golangci-lint-action
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=10m

  go-static:
    name: "go-staticcheck"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WillAbides/setup-go-faster@v1.14.0
        with:
          go-version: '1.22'
      - name: Run static code analysis
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.7"
          install-go: false

  go-test:
    name: go-test
    runs-on: ubuntu-latest
    needs:
    - go-lint
    - go-static
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run unit tests
        run: make test

  go-vet:
    name: "go-vet"
    runs-on: ubuntu-latest
    needs:
    - go-lint
    - go-static
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Run go vet
        run: make vet

  build:
    name: "build-artifact"
    runs-on: ubuntu-latest
    needs:
    - go-test
    - go-vet
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make git -y

      - name: Build (OS=linux-amd64)
        env:
          OS_ARCH: linux-amd64
        run: |
          make clean
          make linux-amd64-container
          make build-${OS_ARCH}

      - name: Save artifacts (OS=linux-amd64)
        uses: actions/upload-artifact@v3
        with:
          name: opct-linux-amd64
          path: |
            build/opct-*

      - name: Build (OS=darwin-arm64)
        env:
          OS_ARCH: darwin-arm64
        run: |
          make clean
          make build-${OS_ARCH}

      - name: Save artifacts (OS=darwin-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: opct-darwin-arm64
          path: |
            build/opct-*
  cmd-report:
    name: "run-report"
    runs-on: ubuntu-latest
    needs:
    - build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: opct-linux-amd64
          path: /tmp/build/

      - name: Running report
        env:
          RESULT_ARTIFACT_URL: "https://openshift-provider-certification.s3.us-west-2.amazonaws.com"
          RESULT_ARTIFACT_VERSION: "v0.4.0/default/4.15.0-20240228-HighlyAvailable-vsphere-None.tar.gz"
          CUSTOM_BUILD_PATH: /tmp/build/opct-linux-amd64
        run: |
          echo "> Downloading sample artifact: ${RESULT_ARTIFACT_URL}/${RESULT_ARTIFACT_VERSION}"
          wget -qO /tmp/result.tar.gz "${RESULT_ARTIFACT_URL}/${RESULT_ARTIFACT_VERSION}"

          echo "> Setting run permissions to OPCT:"
          chmod u+x ${CUSTOM_BUILD_PATH}

          echo "> Running OPCT report:"
          ${CUSTOM_BUILD_PATH} report /tmp/result.tar.gz
