---
name: Lint YAML

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: |
          echo ">> Running YAML lint on data/templates/plugins/"
          yamllint data/templates/plugins/
