---
name: reviewer

on:
  workflow_call: {}

# golangci-lint-action requires those permissions to annotate issues in the PR.
permissions:
  contents: read
  checks: write
  issues: read
  pull-requests: write

env:
  GO_VERSION: 1.22
  GOLANGCI_LINT_VERSION: v1.59

jobs:
  # reviewdog / misspell:  https://github.com/reviewdog/action-misspell
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          # level: warning
          locale: "US"

  # reviewdog / suggester: https://github.com/reviewdog/action-suggester
  go_fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gofmt -w -s .
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: gofmt

  # https://github.com/reviewdog/action-hadolint
  # containerfile:
  #   name: runner / hadolint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4
  #     - name: hadolint
  #       uses: reviewdog/action-hadolint@v1
  #       with:
  #         reporter: github-pr-review
