name: "Push CI Results Image"
on:
  workflow_dispatch:
    inputs:
      results_url:
        description: Google Cloud Storage URI (gs://) to certification results in Prow CI artifact storage
        required: true
      cluster_version:
        description: OpenShift cluster version
        required: true
      platformType:
        description: Name of the platform where certification results were run  (e.g. AWS, vSphere)
        required: true
      descriptor:
        description: Descriptor to append to container image name (e.g. disconnected)
        required: false

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install gsutil
      run: pip install gsutil
    - name: Download certification results
      env:
        RESULTS_URL: ${{ github.event.inputs.results_url }}
      run: |
        gsutil -m cp -r "${RESULTS_URL}" .
        if [ $(ls certification-results/ | wc -l) != 1]; then
          echo 'Expecting single certification result archive' >&2
          ls certification-results/ >&2
          exit 1
        fi
    - name: Build and push image
      env:
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_PASS: ${{ secrets.QUAY_PASS }}
        CLUSTER_VERSION: ${{ github.event.inputs.cluster_version }}
        DESCRIPTOR: ${{ github.event.inputs.descriptor }}
        PLATFORM_TYPE: ${{ github.event.inputs.platformType }}
      run: |
        DATE=$(date +%Y%m%d)
        
        # Login
        podman login -u="${QUAY_USER}" -p="${QUAY_PASS}" quay.io
        
        # Create new empty container image and 
        CONTAINER=$(buildah from scratch)

        # Store certification results in image
        # rename to .tar.gz (.gz extension is stripped by Prow) 
        buildah copy $CONTAINER certification-results/*.tar results.tar.gz
        
        IMAGE_NAME="quay.io/ocp-cert/baseline-results:${CLUSTER_VERSION}-${DATE}"
        
        # Insert descriptor if available
        if [ ! -z "$DESCRIPTOR" ]; then
          IMAGE_NAME="quay.io/ocp-cert/baseline-results:${CLUSTER_VERSION}-${DESCRIPTOR}-${DATE}"
        fi
        
        # Add platformType label
        buildah config --label ocpcert.platform="${PLATFORM_TYPE}" --created-by=redhat-openshift-ecosystem/provider-certification-tool/actions/workflows/push-image.yaml $CONTAINER 
        
        # Commit and push
        buildah commit $CONTAINER "$IMAGE_NAME"
        podman push "$IMAGE_NAME"
