name: Release

on:
  push:
    tags:
      - '*'

env:
  CONTAINER_REPO: quay.io/ocp-cert/opct
  RELEASE_TAG: ${{ github.ref_name }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Workaround step for act
      - name: Install sudo package
        if: env.ACT == 'true'
        run: apt update && apt install sudo

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make git -y

      - name: Build (all OS)
        run: make all

      - name: Build Container and Release to Quay
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASS: ${{ secrets.QUAY_PASS }}
        run: |
          echo "> Logging to Quay.io:"
          podman login -u="${QUAY_USER}" -p="${QUAY_PASS}" quay.io

          echo "> Build container image:"
          podman build -t ${CONTAINER_REPO}:${RELEASE_TAG} -f hack/Containerfile.ci .

          echo "> Publish container image:"
          podman push ${CONTAINER_REPO}:${RELEASE_TAG}

      # https://github.com/mikepenz/release-changelog-builder-action#configuration
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          configuration: ".github/workflows/changelog-configuration.json"

      # https://github.com/softprops/action-gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            openshift-provider-cert-*
            opct-*
          body: |
            ## Changelog
            ${{steps.github_release.outputs.changelog}}
            
            ## Container Images
            - [${CONTAINER_REPO}:${RELEASE_TAG}](https://quay.io/repository/ocp-cert/opct?tab=tags)