name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Workaround step for act
      - name: Install sudo package
        if: env.ACT == 'true'
        run: apt update && apt install sudo

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make git -y

      - name: Build (all OS)
        run: make all
        env:
          RELEASE_TAG: ${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            openshift-provider-cert*

      - name: Build Container and Release to Quay
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          IMAGE: quay.io/ocp-cert/opct
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASS: ${{ secrets.QUAY_PASS }}
        run: |
          echo "> Logging to Quay.io:"
          podman login -u="${QUAY_USER}" -p="${QUAY_PASS}" quay.io

          echo "> Build container image:"
          podman build -t ${IMAGE}:${VERSION} -f hack/Containerfile.ci .

          echo "> Publish container image:"
          podman push ${IMAGE}:${VERSION}